export const PLAYER_PHOTOS = {
  "Tanzim Hasan Sakib": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Tanzim_Hasan_Sakib_in_2024.jpg/250px-Tanzim_Hasan_Sakib_in_2024.jpg",
  "Fazalhaq Farooqi": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Fazalhaq_Farooqi.jpg/250px-Fazalhaq_Farooqi.jpg",
  "DA Warner": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/David_Warner.jpg/250px-David_Warner.jpg",
  "Rishad Hossain": "https://upload.wikimedia.org/wikipedia/commons/8/84/Rishad_Hossain%2C_2025-02-08_Fortune_Barishal_BPL_2025_Champions_Trophy_Presentation_Dhaka_%28PID-0003668%29_%28cropped%29.jpg",
  "Rashid Khan": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Rashid_Khan.jpg/250px-Rashid_Khan.jpg",
  "JC Buttler": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Jos_Buttler_in_2023.jpg/250px-Jos_Buttler_in_2023.jpg",
  "Arshdeep Singh": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Prime_Minister_Of_Bharat_Shri_Narendra_Damodardas_Modi_with_Arshdeep_Singh_Family_%28Cropped%29.jpg/250px-Prime_Minister_Of_Bharat_Shri_Narendra_Damodardas_Modi_with_Arshdeep_Singh_Family_%28Cropped%29.jpg",
  "SA Yadav": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Suryakumar_Yadav_in_PMO_New_Delhi.jpg/250px-Suryakumar_Yadav_in_PMO_New_Delhi.jpg",
  "A Zampa": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Adam_Zampa_2023.jpg/250px-Adam_Zampa_2023.jpg",
  "JJ Bumrah": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Jasprit_Bumrah_in_PMO_New_Delhi.jpg/250px-Jasprit_Bumrah_in_PMO_New_Delhi.jpg",
  "H Klaasen": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Heinrich_Klaasen_%28cropped%29.jpg/250px-Heinrich_Klaasen_%28cropped%29.jpg",
  "MP Stoinis": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Marcus_Stoinis_%28cropped%29.jpg/250px-Marcus_Stoinis_%28cropped%29.jpg",
  "AD Russell": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Andre_Russell_in_2024.jpg/250px-Andre_Russell_in_2024.jpg",
  "RL Chase": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Roston_Chase_in_2024.jpg/250px-Roston_Chase_in_2024.jpg",
  "AU Rashid": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Adil_Rashid.jpg/250px-Adil_Rashid.jpg",
  "A Nortje": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Anrich_Nortje_in_2023.jpg/250px-Anrich_Nortje_in_2023.jpg",
  "PD Salt": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/2_02_Phil_Salt.jpg/250px-2_02_Phil_Salt.jpg",
  "Aaron Jones": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Aaron_Jones_WFT_vs_Packers_OCT2021_%28cropped%29.jpg/250px-Aaron_Jones_WFT_vs_Packers_OCT2021_%28cropped%29.jpg",
  "RR Pant": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Rishabh_Pant.jpg/250px-Rishabh_Pant.jpg",
  "KA Maharaj": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/New_face_6-_Keshav_Maharaj.jpg/250px-New_face_6-_Keshav_Maharaj.jpg",
  "HH Pandya": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Hardik_Pandya_in_PMO_New_Delhi.jpg/250px-Hardik_Pandya_in_PMO_New_Delhi.jpg",
  "K Rabada": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Rabada.jpg/250px-Rabada.jpg",
  "Naveen-ul-Haq": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Naveen-ul-Haq_in_2023.jpg/250px-Naveen-ul-Haq_in_2023.jpg",
  "AGS Gous": "https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_320,q_50/lsci/db/PICTURES/CMS/380700/380749.png"
};
